# YAML linting configuration
# https://yamllint.readthedocs.io/en/stable/configuration.html

extends: default

rules:
  # Allow longer lines (default is 80)
  line-length:
    max: 120
    level: warning

  # Allow duplicate keys (sometimes needed in anchors/aliases)
  key-duplicates:
    level: error

  # Indentation rules
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false

  # Comments rules
  comments:
    min-spaces-from-content: 1
    require-starting-space: true
    ignore-shebangs: true

  # Trailing spaces
  trailing-spaces: enable

  # New line at end of file
  new-line-at-end-of-file: enable

  # Document start markers (---)
  document-start:
    present: false

  # Empty lines
  empty-lines:
    max: 2
    max-start: 0
    max-end: 0

  # Bracket spacing
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0

  # Truthy values
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
    check-keys: false

ignore: |
  .venv/
  venv/
  node_modules/
  dist/
  build/
  _build/
  .eggs/
